import { PROJECT_FILE_VERSION, type MediaItem, type ProjectFile } from '@shared'
import { useTimelineStore } from '../../stores/timelineStore'
import { useMediaStore } from '../../stores/mediaStore'
import { projectService } from '../../services/projectService'

/** Waveforms are a derived cache, not project data — they're regenerated by the
 * backfill on load, so we neither persist nor trust persisted ones (older files
 * may hold stale/misaligned peaks). */
function stripWaveforms(items: MediaItem[]): MediaItem[] {
  return items.map((item) => {
    const next = { ...item }
    delete next.waveform
    return next
  })
}

/** Snapshot the current edit state into a serializable project. */
export function currentProject(): ProjectFile {
  return {
    version: PROJECT_FILE_VERSION,
    model: useTimelineStore.getState().model,
    media: stripWaveforms(useMediaStore.getState().items)
  }
}

/** Replace the current session with a loaded project. */
export function applyProject(project: ProjectFile): void {
  useMediaStore.getState().setItems(stripWaveforms(project.media))
  useTimelineStore.getState().loadModel(project.model)
}

export async function saveCurrentProject(): Promise<void> {
  await projectService.save(currentProject())
}

export async function openProject(): Promise<void> {
  const result = await projectService.load()
  if (result.ok && result.value) applyProject(result.value)
}
